sudo: required
services: 
  - docker

before_install:
  - docker build -t andinianst93/aws-static-next-app -f Dockerfile.dev .

script:
  - docker run -e CI=true andinianst93/aws-static-next-app npm run test