name: CI/CD Pipeline
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
      if: runner.os == 'Linux'

    - name: Build docker image
      run: docker build -t andinianst93/aws-static-next-app -f Dockerfile.dev .

    - name: Run tests
      run: docker run -e CI=true andinianst93/aws-static-next-app npm run test